# Generated by Django 3.1.3 on 2021-02-20 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('m', 'м'), ('f', 'ж')], max_length=1)),
                ('birthday', models.DateField(db_index=True)),
                ('hometown', models.CharField(max_length=200)),
                ('balance', models.PositiveBigIntegerField(default=0)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ('create_at',),
            },
        ),
    ]
