# Generated by Django 3.1.3 on 2021-02-20 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcategory_id',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='for_product_id',
            new_name='for_product',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='from_user_id',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='category_id',
            new_name='category',
        ),
    ]
