# Generated by Django 3.1.3 on 2020-11-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20201106_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imagesPath',
            field=models.TextField(default='', verbose_name=models.ImageField(upload_to='products/img/')),
        ),
    ]
