# Generated by Django 3.1.3 on 2021-02-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210221_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.CharField(default='https://raw.githubusercontent.com/IKolyas/static/master/store/media/images/', max_length=500),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата обновления'),
        ),
    ]
