# Generated by Django 3.1.3 on 2020-11-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_image_imagespath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imagesPath',
            field=models.TextField(default=models.ImageField(upload_to='products/img/'), verbose_name=models.ImageField(upload_to='products/img/')),
        ),
    ]
