# Generated by Django 3.1.3 on 2020-11-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20201106_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imagesPath',
            field=models.CharField(default=models.ImageField(upload_to='products/img/'), max_length=100, verbose_name='путь'),
        ),
    ]
