# Generated by Django 3.1.3 on 2020-11-07 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20201106_0340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('title',), 'verbose_name': 'подкатегория', 'verbose_name_plural': 'подкатегории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.IntegerField(blank=True, default='', verbose_name='штрихкод'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='webapp.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=50, verbose_name='подкатегория'),
        ),
    ]
