# Generated by Django 3.1.3 on 2020-11-07 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20201108_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='webapp.product'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.category', verbose_name='категория'),
        ),
    ]
