# Generated by Django 3.1.3 on 2020-11-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20201114_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('1', '1 - спальные'), ('1.5', '1.5 - спальные'), ('2', '2 - спальные')], max_length=3, verbose_name='размер'),
        ),
        migrations.DeleteModel(
            name='Sizes',
        ),
    ]
