# Generated by Django 3.1.3 on 2020-11-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20201114_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=16, verbose_name='цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('1', '1 - спальные'), ('3', '3 - спальные'), ('2', '2 - спальные')], max_length=5, verbose_name='размер'),
        ),
    ]
